version: "3"

services:
  kafka:
    image: bitnami/kafka:latest
    networks:
      - kafka
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS= EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      - kafka
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  kafka: