order:
  bpmn:
    process:
      id: Process_0qzoo7d
zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
server:
  port: 8080
routers:
  orders:
    host: localhost
    grpc-port: 9091
  warehouse:
    host: localhost
    grpc-port: 9092
  users:
    host: localhost
    grpc-port: 9093
