zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
spring:
  datasource:
    url: jdbc:h2:mem:order_database
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  kafka:
    bootstrap-servers: localhost:29092
  h2:
    console:
      enabled: true
server:
  port: 8080