spring:
  datasource:
    url: jdbc:h2:mem:order_database
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  kafka:
    bootstrap-servers: localhost:29092
  h2:
    console:
      enabled: true
grpc:
  server:
    port: 9091
temporal:
  enabled: false
  worker-name: OrderServiceActivity
  namespace: default
  host: localhost
  port: 7233
