spring:
  datasource:
    url: jdbc:h2:mem:warehouse_database
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        spring.json.add.type.headers: false
grpc:
  server:
    port: 9092
temporal:
  enabled: false
  worker-name: ProductServiceActivity
  namespace: default
  host: localhost
  port: 7233
