zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
spring:
  datasource:
    url: jdbc:h2:mem:warehouse_database
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        spring.json.add.type.headers: false
server:
  port: 8083
grpc:
  server:
    port: 9093